name: Unity Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Unity - Build
        run: ./.scripts/build.bat
      
      - name: Create Archive
        run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

      - name: Upload a Build Artifact
        uses: action/upload-artifact@2.2.2
        with:
          name: Game
          path: ./game.zip
          retention-days: 9